version: "3"

services:
  app:
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    build:
      context: ./node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: name
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
